import type {
  Shop,
  Order,
  DashboardStats,
  ShopStaff,
} from "@/types";

// ─── Demo Shop ───────────────────────────────────────────────────────────────
export const DEMO_SHOP: Shop = {
  id: "demo-shop-001",
  owner_id: "demo-user-001",
  shop_name: "Ravi Xerox & Print",
  address: "12, MG Road, Near Bus Stand",
  city: "Hyderabad",
  state: "Telangana",
  pincode: "500001",
  phone: "9876543210",
  email: "ravi.xerox@gmail.com",
  photos: [],
  services: ["B&W Printing", "Color Printing", "Scanning", "Binding", "Lamination"],
  pricing: {
    bw_a4: 2,
    color_a4: 10,
    bw_a3: 4,
    color_a3: 20,
    binding_spiral: 30,
    binding_soft: 50,
    delivery: 20,
  },
  timings: {
    mon: "9:00 AM - 9:00 PM",
    tue: "9:00 AM - 9:00 PM",
    wed: "9:00 AM - 9:00 PM",
    thu: "9:00 AM - 9:00 PM",
    fri: "9:00 AM - 9:00 PM",
    sat: "9:00 AM - 7:00 PM",
    sun: "Closed",
  },
  rating_avg: 4.6,
  total_reviews: 128,
  total_orders: 2340,
  is_approved: true,
  is_open: true,
  is_active: true,
  created_at: "2025-01-15T09:00:00Z",
  updated_at: new Date().toISOString(),
};

// ─── Demo Orders ──────────────────────────────────────────────────────────────
const now = new Date();
const mins = (m: number) => new Date(now.getTime() - m * 60000).toISOString();

export const DEMO_ORDERS: Order[] = [
  {
    id: "ord-001",
    order_number: "ORD-202604-00042",
    customer_id: "cust-001",
    shop_id: "demo-shop-001",
    customer_name: null,
    customer_phone: null,
    short_token: null,
    files: [{ url: "#", name: "Assignment_Final.pdf", size: 2400000, pages: 24 }],
    print_config: { color: "bw", size: "A4", copies: 2, binding: "spiral", duplex: false },
    special_instructions: "Please use 80gsm paper only",
    total_pages: 48,
    total_amount: 126,
    status: "placed",
    status_history: [{ status: "placed", timestamp: mins(3) }],
    estimated_completion: null,
    rejection_reason: null,
    created_at: mins(3),
    updated_at: mins(3),
    customer: { id: "cust-001", email: "student1@example.com", user_metadata: { name: "Arjun Reddy", phone: "9123456780" } },
  },
  {
    id: "ord-002",
    order_number: "ORD-202604-00041",
    customer_id: "cust-002",
    shop_id: "demo-shop-001",
    customer_name: null,
    customer_phone: null,
    short_token: null,
    files: [
      { url: "#", name: "Resume_2026.pdf", size: 850000, pages: 2 },
      { url: "#", name: "Cover_Letter.pdf", size: 320000, pages: 1 },
    ],
    print_config: { color: "color", size: "A4", copies: 5, binding: "none", duplex: false },
    special_instructions: null,
    total_pages: 15,
    total_amount: 750,
    status: "placed",
    status_history: [{ status: "placed", timestamp: mins(8) }],
    estimated_completion: null,
    rejection_reason: null,
    created_at: mins(8),
    updated_at: mins(8),
    customer: { id: "cust-002", email: "priya@example.com", user_metadata: { name: "Priya Sharma", phone: "9876501234" } },
  },
  {
    id: "ord-003",
    order_number: "ORD-202604-00040",
    customer_id: "cust-003",
    shop_id: "demo-shop-001",
    customer_name: null,
    customer_phone: null,
    short_token: null,
    files: [{ url: "#", name: "Project_Report.pdf", size: 5200000, pages: 52 }],
    print_config: { color: "bw", size: "A4", copies: 1, binding: "soft", duplex: true },
    special_instructions: null,
    total_pages: 26,
    total_amount: 102,
    status: "accepted",
    status_history: [
      { status: "placed", timestamp: mins(45) },
      { status: "accepted", timestamp: mins(40) },
    ],
    estimated_completion: new Date(now.getTime() + 20 * 60000).toISOString(),
    rejection_reason: null,
    created_at: mins(45),
    updated_at: mins(40),
    customer: { id: "cust-003", email: "rohan@example.com", user_metadata: { name: "Rohan Mehta", phone: "9988776655" } },
  },
  {
    id: "ord-004",
    order_number: "ORD-202604-00039",
    customer_id: "cust-004",
    shop_id: "demo-shop-001",
    customer_name: null,
    customer_phone: null,
    short_token: null,
    files: [{ url: "#", name: "Slides_Presentation.pdf", size: 8100000, pages: 30 }],
    print_config: { color: "color", size: "A4", copies: 3, binding: "none", duplex: false },
    special_instructions: "Urgent — needed by 2 PM",
    total_pages: 90,
    total_amount: 900,
    status: "printing",
    status_history: [
      { status: "placed", timestamp: mins(90) },
      { status: "accepted", timestamp: mins(85) },
      { status: "printing", timestamp: mins(20) },
    ],
    estimated_completion: new Date(now.getTime() + 10 * 60000).toISOString(),
    rejection_reason: null,
    created_at: mins(90),
    updated_at: mins(20),
    customer: { id: "cust-004", email: "ananya@example.com", user_metadata: { name: "Ananya Singh", phone: "9654321987" } },
  },
  {
    id: "ord-005",
    order_number: "ORD-202604-00038",
    customer_id: "cust-005",
    shop_id: "demo-shop-001",
    customer_name: null,
    customer_phone: null,
    short_token: null,
    files: [{ url: "#", name: "Notice_Board.pdf", size: 400000, pages: 4 }],
    print_config: { color: "bw", size: "A3", copies: 10, binding: "none", duplex: false },
    special_instructions: null,
    total_pages: 40,
    total_amount: 160,
    status: "ready",
    status_history: [
      { status: "placed", timestamp: mins(180) },
      { status: "accepted", timestamp: mins(170) },
      { status: "printing", timestamp: mins(100) },
      { status: "ready", timestamp: mins(30) },
    ],
    estimated_completion: null,
    rejection_reason: null,
    created_at: mins(180),
    updated_at: mins(30),
    customer: { id: "cust-005", email: "college@example.com", user_metadata: { name: "Srinivas Rao", phone: "9700000001" } },
  },
  {
    id: "ord-006",
    order_number: "ORD-202604-00037",
    customer_id: "cust-006",
    shop_id: "demo-shop-001",
    customer_name: null,
    customer_phone: null,
    short_token: null,
    files: [{ url: "#", name: "Invoice_March.pdf", size: 210000, pages: 2 }],
    print_config: { color: "color", size: "A4", copies: 1, binding: "none", duplex: false },
    special_instructions: null,
    total_pages: 2,
    total_amount: 20,
    status: "completed",
    status_history: [
      { status: "placed", timestamp: mins(300) },
      { status: "accepted", timestamp: mins(290) },
      { status: "printing", timestamp: mins(250) },
      { status: "ready", timestamp: mins(220) },
      { status: "completed", timestamp: mins(200) },
    ],
    estimated_completion: null,
    rejection_reason: null,
    created_at: mins(300),
    updated_at: mins(200),
    customer: { id: "cust-006", email: "biz@example.com", user_metadata: { name: "Kavitha Nair", phone: "9811223344" } },
  },
];

// ─── Demo Stats ───────────────────────────────────────────────────────────────
export const DEMO_STATS: DashboardStats = {
  pendingOrders: 2,
  ordersToday: 14,
  revenueToday: 3840,
  avgCompletionMins: 28,
  activeCustomers: 9,
  completedToday: 11,
};

// ─── Demo Staff ───────────────────────────────────────────────────────────────
export const DEMO_STAFF: ShopStaff[] = [
  {
    id: "staff-001",
    shop_id: "demo-shop-001",
    user_id: "demo-user-001",
    role: "owner",
    permissions: {},
    created_at: "2025-01-15T09:00:00Z",
    user: { email: "owner@demo.com", user_metadata: { name: "Ravi Kumar" } },
  },
  {
    id: "staff-002",
    shop_id: "demo-shop-001",
    user_id: "demo-user-002",
    role: "manager",
    permissions: { manage_orders: true, view_analytics: true },
    created_at: "2025-03-01T10:00:00Z",
    user: { email: "manager@demo.com", user_metadata: { name: "Suresh Babu" } },
  },
  {
    id: "staff-003",
    shop_id: "demo-shop-001",
    user_id: "demo-user-003",
    role: "staff",
    permissions: { manage_orders: true },
    created_at: "2025-04-01T10:00:00Z",
    user: { email: "staff@demo.com", user_metadata: { name: "Lakshmi Devi" } },
  },
];

// ─── Analytics Demo Data ──────────────────────────────────────────────────────
export const DEMO_ANALYTICS = {
  revenue: [
    { date: "Apr 19", revenue: 2100, orders: 8 },
    { date: "Apr 20", revenue: 3400, orders: 14 },
    { date: "Apr 21", revenue: 1800, orders: 7 },
    { date: "Apr 22", revenue: 4200, orders: 18 },
    { date: "Apr 23", revenue: 2900, orders: 11 },
    { date: "Apr 24", revenue: 3800, orders: 15 },
    { date: "Apr 25", revenue: 3840, orders: 14 },
  ],
  statusBreakdown: [
    { name: "Completed", value: 78, color: "#10B981" },
    { name: "Cancelled", value: 8, color: "#EF4444" },
    { name: "Rejected", value: 4, color: "#F59E0B" },
    { name: "Active", value: 10, color: "#2E8B57" },
  ],
  peakHours: [
    { hour: "9 AM", orders: 3 }, { hour: "10 AM", orders: 7 },
    { hour: "11 AM", orders: 12 }, { hour: "12 PM", orders: 9 },
    { hour: "1 PM", orders: 5 }, { hour: "2 PM", orders: 11 },
    { hour: "3 PM", orders: 14 }, { hour: "4 PM", orders: 10 },
    { hour: "5 PM", orders: 8 }, { hour: "6 PM", orders: 6 },
    { hour: "7 PM", orders: 4 }, { hour: "8 PM", orders: 2 },
  ],
  services: [
    { name: "B&W A4", count: 124 }, { name: "Color A4", count: 87 },
    { name: "B&W A3", count: 34 }, { name: "Color A3", count: 22 },
    { name: "Binding", count: 45 }, { name: "Scanning", count: 18 },
  ],
};
